version: '3.8'

services:

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=ewacademy
      - POSTGRES_USER=erickwendel
      - POSTGRES_PASSWORD=erick
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    ports:
      - "5432:5432"
